spring.application.name=backend

# ============================================================
# SERVER
# ============================================================

server.port=8080

# ============================================================
# POSTGRESQL
# ============================================================

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/credlens
spring.datasource.username=credlens
spring.datasource.password=credlens_dev
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================================
# JPA
# ============================================================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ============================================================
# ML SERVICE
# ============================================================
ml.service.base-url=http://localhost:8001